### ISSUE TITLE
Make classes completely unevaluated

### ISSUE THREAD

**Issue by asmeurer** [Quansight/ndindex#1]
RIght now, classes canonicalize in their constructors. But a better design would be to not do anything in the constructors, other than basic type checking. There should then be some sort of canonicalize method (but not called "canonicalize", maybe we can use `doit` like SymPy), which applies the normalization. This would also allow classes to use `__init__` instead of `__new__`.

Any method that assumes the inputs are canonical (e.g., no None step in Slice) would call this method first. 

This way, people can represent indices exactly, without them being normalized. Things like Slice(0, n) and Slice(n) could be distinguishable from one another.

Open questions:

- What sorts of things should be considered OK for type checking in constructors? I think wrong types (like non-integer) is OK. But what about, for instance, `Tuple(..., ...)` (tuples can only have one ellipsis)?

- What's the standard way to create objects if you do want canonicalization? A good way would normally be to make lowercase functions that call `doit` for you, but we can't use `slice` and `tuple`, and the ellipsis class will probably be called `ellipsis` since `Ellipsis` is taken. 

- Should `ndindex()` call doit() automatically by default? My thinking is yes. Most people want a canonical form. This issue is just for those who don't. This also would solve the above point.

**Comment by asmeurer** [comment]
Also things like step being 0. My thinking is that if doit() were to raise an error, that is something that should have been raised in the constructor. There's no need to allow Slice(0, 0, 0) because it's meaningless and no operation on it would be successful. We also, even with this change, want to maintain the design that the index objects specifically represent indexes on numpy arrays.

**Comment by scopatz** [comment]
Isn't `Slice(0,0,0)` a valid reference to the start of the array?

**Comment by asmeurer** [comment]
No, step size 0 unconditionally gives an error

```py
>>> np.array([0])[0:0:0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: slice step cannot be zero
```

**Comment by asmeurer** [comment]
I think we should use `reduce` for this. `shape` can become an optional parameter. If it isn't passed, the object is canonicalized as much as possible without any shape information.

**Comment by scopatz** [comment]
That makes sense
