### ISSUE TITLE
Documentation organization

### ISSUE THREAD

**Issue by asmeurer** [Quansight/ndindex#33]
Right now the bulk of the documentation is in the docstrings. 

Presently, the docs have an "api.html" page that lists all the docstrings for every class in the library https://quansight.github.io/ndindex/api.html. 

I also want to add some narrative documentation (i.e., in Sphinx only, not docstrings), for instance, describing different intricacies of indexing. For example, I want to write a document that explains how slice indexing works.

I am wondering what the best way to organize the documentation would be. Should we keep the API documentation separate from the above discussions? Or would it make more sense to have separate pages for each index type, which has the discussion in one section and the API documentation in another? Conversely, if we decide to keep the API docs separate, is it OK to keep it all on one page or is it better to split into separate pages for each class?

@melissawm can you give your thoughts on this?

**Comment by melissawm** [comment]
I think for now it makes sense to keep the API all in one page, but I'd vote for separating narrative docs from the API reference, with links when appropriate. The page you described, for example, about how slice indexing works, sounds like an [Explanation](https://documentation.divio.com/explanation/) while there might also be one or more [Tutorials](https://documentation.divio.com/tutorials/) and the API is separate from all that.

**Comment by asmeurer** [comment]
This is relevant to the documentation PR that I will be opening very soon (either today or tomorrow), so let's keep it open for now. 

We also may want to revisit the idea of splitting the API once we have a lot more methods. I don't know if it's still good to keep everything together or to split. I've seen projects that do both ways.
