### ISSUE TITLE
Update list of features on the README

### ISSUE THREAD

**Issue by asmeurer** [Quansight/ndindex#53]
Some new features have been implemented that aren't mentioned in the README yet.

**Comment by asmeurer** [comment]
Also a lot of the text in the README should be converted into cross-reference links to other parts of the documentation, since it is also used as the home page at https://quansight.github.io/ndindex/index.html.

**Comment by asmeurer** [comment]
A problem is that relative links (Sphinx cross-references) will work correctly in the documentation, but that will give 404s on the GitHub README.

**Comment by melissawm** [comment]
Maybe the solution is to have the README separate from the index for the html docs. Sounds more reasonable if we want richer links. The downside is having two separate documents to update.

**Comment by asmeurer** [comment]
Yes, I went ahead and split them. The README is now much shorter with just some basic examples. The main documentation page will have the more detailed information.
