### ISSUE TITLE
hash(ndindex_obj) != hash(raw_obj)

### ISSUE THREAD

**Issue by asmeurer** [Quansight/ndindex#88]
ndindex objects are equal to the equivalent raw objects. But they define a separate hash, which can cause issues if the raw object is also hashable:

```py
>>> hash(Tuple(1, ...))
3933283291967008864
>>> hash((1, ...))
3712794302832630381
>>> Tuple(1, ...) == (1, ...)
True
```

In general it would not be a good idea to use a raw object in a hashable context, because only a subset of raw indices are hashable (slices and arrays are not hashable), but it would still be a good idea to make the hashes match when they exist (see  https://www.asmeurer.com/blog/posts/what-happens-when-you-mess-with-hashing-in-python/).

**Comment by asmeurer** [comment]
We also have 

```py
>>> ndindex(False) == ndindex(0)
False
>>> False == 0
True
```

because

```py
>>> ndindex(False).raw
array(False)
```

Not to mention this behavior

```py
>>> ndindex([0, 1]) == np.array([0, 1])
True
>>> np.array([0, 1]) == ndindex([0, 1])
array([False, False])
```

which we can't do anything about. The best recommendation is to always convert any index object into an ndindex object, and manipulate that, and only use a raw index type (`.raw`) at the end when you actually index an array.

**Comment by asmeurer** [comment]
Fix at https://github.com/Quansight/ndindex/pull/93

**Comment by telamonian** [comment]
> Not to mention this behavior
> 
> ```python
> >>> ndindex([0, 1]) == np.array([0, 1])
> True
> >>> np.array([0, 1]) == ndindex([0, 1])
> array([False, False])
> ```

@asmeurer In your ideal world, which of the following would be the behavior for `ndarray` vs `NDIndex` equality?

A)

```
ndindex([0, 1]) == np.array([0, 1])
> array([True, True])
np.array([0, 1]) == ndindex([0, 1])
> array([True, True])
```

or B)

```
ndindex([0, 1]) == np.array([0, 1])
> True
np.array([0, 1]) == ndindex([0, 1])
> True
```

Both can be done. I'd argue for A), since that's now the expected behavior for "array-like" objects (as defined by numpy as of 1.17, I think?). B) is also doable, but it will have to have the side-effect that `isinstance(ndindex([0, 1]), np.ndarray)` is `True`

**Comment by asmeurer** [comment]
I would prefer it if I could make them both give True. == giving an array makes very basic things like checking if an index is in a list or dictionary difficult, because bool() fails on arrays. And anyway, an ndindex array index object is *not* an array-like. See https://quansight.github.io/ndindex/type-confusion.html#integerarray-and-booleanarray

**Comment by telamonian** [comment]
I opened a new issue for this over at #95. Let's continue the conversation there
